### ISSUE TITLE
microk8s install instructions are incorrect

### ISSUE THREAD

**Issue by salilhpe** [openebs/mayastor-docs#188]
Currently following command is to be used:

` helm install mayastor mayastor/mayastor -n mayastor --create-namespace  --set values.csi.node.kubeletDir="/var/snap/microk8s/common/var/lib/kubelet
`
But **values.csi.node.kubeletDir** is wrong,  it should be **csi.node.kubeletDir**
i.e. the correct command is :

`helm install mayastor mayastor/mayastor -n mayastor --create-namespace  --set csi.node.kubeletDir="/var/snap/microk8s/common/var/lib/kubelet"`

**Comment by tiagolobocastro** [comment]
This is now fixed, thanks @salilhpe !
