### ISSUE TITLE
Error creating mayastor storageclass due ioTimeout option

### ISSUE THREAD

**Issue by jcalvilloitrs** [openebs/mayastor-docs#23]
I tried to create mayastore storageclass using next example:

https://mayastor.gitbook.io/introduction/quickstart/configure-mayastor#create-mayastor-storageclass-s

but I´ve got:
`Error from server (BadRequest): error when creating "STDIN": StorageClass in version "v1" cannot be handled as a StorageClass: v1.StorageClass.Parameters: ReadString: expects " or n, but found 6, error found in #10 byte of ...|Timeout":60,"protoco|..., bigger context ...|name":"mayastor-nvmf"},"parameters":{"ioTimeout":60,"protocol":"nvmf","repl":"1"},"provisioner":"io.|...
`

If I remove line 9, I can create it:

`ioTimeout: 60`

**Comment by GlennBullingham** [comment]
Closing as stale
