### ISSUE TITLE
Mayastor with builtin etcd 

### ISSUE THREAD

**Issue by uhlhosting** [openebs/mayastor-docs#29]
Greetings,

It seems for me personally this part of the docs put me in a very difficult situation to debug: https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#etcd has no examples on a mayatstor deployment when etcd its already part of the k8s cluster, like in case of Talos.dev .

Would be ideal when you mention that mayastor needs etcd, and that users are responsible for installing it, what about where its installed already how do we link that to mayastor, without the need to have 2 etcd deployments, since if we apply the examples given by the docs, we will end up at least on Talos OS deployments with 2 different etcd deployments. 

Best/ideal would be when mayastor can detect if etcd is present, or a switch to allow the deployment of mayastor in a ready etcd os or in an os where etcd lacks.

After deploying all that was to deploy, alto our cluster has etcd out of the box we get:

```
[2021-12-17T23:43:34.090193527+00:00 ERROR mayastor::persistent_store:persistent_store.rs:89] Failed to connect to etcd on endpoint mayastor-etcd:2379. Retrying...
```

Following commands will indeed deploy etcd yet like mentioned above, we already run etcd.

Would like to know how or what we can use when we have etcd in place. Seems by default this etcd is not known to mayastor, and neither is this much documented, or maybe I missed it out.

```
kubectl apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/etcd/statefulset.yaml 
kubectl apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/etcd/svc.yaml
kubectl apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/etcd/svc-headless.yaml
```

**Comment by GlennBullingham** [comment]
Thanks for the feedback @uhlhosting 

Originally it had been planned to implement a means to allow users to "bring their own" etcd instance and this is what the documentation makes reference to.  Delivery of this been deferred until a later release (although is being actively planned), so we'll update the documentation at this time to remove the direction for users to install their own.  That being so, at this time the only way to use Mayastor practically is to deploy it with its own dedicated instance of etcd as per the quickstart instructions.
