### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by Daxcor69** [openebs/mayastor-docs#52]
On  "Deploy Mayastor"  the very last command:

```
kubectl mayastor get nodes
```

should read
```
kubectl -n mayastor get nodes
```

**Comment by tiagolobocastro** [comment]
The command is actually referencing our kubectl plugin.
Right above, it reads:
"The number and status of mayastor pods can be observed by using the [Mayastor kubectl plugin](https://mayastor.gitbook.io/introduction/reference/kubectl-plugin)"
Please take a look [here](https://mayastor.gitbook.io/introduction/reference/kubectl-plugin.
