### ISSUE TITLE
Control Plane section is empty

### ISSUE THREAD

**Issue by rhrytskiv** [openebs/mayastor-docs#67]
https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#control-plane

**Comment by rhrytskiv** [comment]
also, if it's not required at all in 1.x, why does upgrade documentation mention it?

Upgrades from v1.0.1 are disruptive - data plane and **control plane pods** must be unscheduled, and hence all applications using Mayastor must be volumes stopped prior to performing the update.

**Comment by GlennBullingham** [comment]
Appears to be a formatting issue - "Control plane" is supposed to be a heading, under which "CSI node plugin", "Core agents" et al are sub-sections but currently isn't,  giving the false impression that it's an empty section.  We'll take a look at it.

Thanks for catching it.
