### ISSUE TITLE
Data Plane link does not work - 404

### ISSUE THREAD

**Issue by rhrytskiv** [openebs/mayastor-docs#69]
https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#data-plane

https://raw.githubusercontent.com/openebs/mayastor/master/v1.0.2/mayastor-daemonset.yaml

**Comment by GlennBullingham** [comment]
Yes, that URL had been incorrectly transcribed during the update to the documentation for the v1.0.3 release.

Fixed: https://github.com/openebs/mayastor-docs/pull/68

Apologies for any inconvenience caused.

**Comment by rhrytskiv** [comment]
Sorry, so where I can find working link for DataPlane for 1.0.3? Because the one of the website right now still produces 404.
https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#data-plane

**Comment by rhrytskiv** [comment]
Is this the one https://raw.githubusercontent.com/openebs/mayastor/v1.0.3/deploy/mayastor-daemonset.yaml ?

**Comment by rhrytskiv** [comment]
@GlennBullingham
